Build Python 3.6 from source.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -45,41 +45,95 @@ cp ~/.acorn/rutorrent "$(whoami)/config.php"
 # ensure ~/src directory exists
 mkdir -p ~/src
 
-# reinstall go
-mkdir -p ~/tmp
-wget https://dl.google.com/go/go1.14.linux-amd64.tar.gz -O ~/tmp/go.tar.gz
-tar -xvf ~/tmp/go.tar.gz -C ~/tmp
-rm -rf ~/src/go
-mv ~/tmp/go ~/src
-rm -rf ~/tmp
+# install go
+version="$(~/src/go/bin/go version 2>/dev/null || true)"
+if [[ "$version" == "go version go1.14 linux/amd64" ]]; then
+  echo "go already installed"
+  echo "  $version"
+else
+  mkdir -p ~/tmp
+  wget https://dl.google.com/go/go1.14.linux-amd64.tar.gz \
+    -O ~/tmp/go.tar.gz
+  tar -xvf ~/tmp/go.tar.gz -C ~/tmp
+  rm -rf ~/src/go
+  mv ~/tmp/go ~/src
+  rm -rf ~/tmp
+  version="$(~/src/go/bin/go version 2>/dev/null)"
+  if [[ "$version" != "go version go1.14 linux/amd64" ]]; then
+    echo "go installation failed"
+    echo "  $version"
+    exit 0
+  fi
+fi
+
+# install python 3.6
+version="$(~/src/python3/python --version 2>/dev/null || true)"
+if [[ "$version" == "Python 3.6.3" ]]; then
+  echo "python already installed"
+  echo "  $version"
+else
+  mkdir -p ~/tmp
+  wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz \
+    -O ~/tmp/python.tar.gz
+  tar -xvf ~/tmp/python.tar.gz -C ~/tmp
+  rm -rf ~/src/python3
+  mv ~/tmp/Python-3.6.3 ~/src/python3
+  rm -rf ~/tmp
+  cd ~/src/python3
+  ./configure
+  make
+  version="$(~/src/python3/python --version 2>/dev/null)"
+  if [[ "$version" != "Python 3.6.3" ]]; then
+    echo "python installation failed"
+    echo "  $version"
+    exit 0
+  fi
+fi
+
+# install pip for python 3.6
+version="$(~/src/python3/python -m pip --version 2>/dev/null || true)"
+if [[ "$version" == "pip 20.2.3"* ]]; then
+  echo "pip already installed"
+  echo "  $version"
+else
+  wget -qO- https://bootstrap.pypa.io/get-pip.py | ~/src/python3/python
+  version="$(~/src/python3/python -m pip --version 2>/dev/null)"
+  if [[ "$version" != "pip 20.2.3"* ]]; then
+    echo "pip installation failed"
+    echo "  $version"
+    exit 0
+  fi
+fi
 
 # configure ~/bin
 mkdir -p ~/bin
 cp ~/.acorn/sickchill ~/bin/sickchill
 
-# install pip3 virtualenv
-pip3 install --user virtualenv
-~/.local/bin/virtualenv ~/src/pip3 --system-site-packages
-
 # install sickchill and dependencies
-git clone https://github.com/SickChill/SickChill.git ~/SickChill 2>/dev/null || true
+git clone https://github.com/SickChill/SickChill.git ~/SickChill 2>/dev/null \
+  || true
 cd ~/SickChill
 git fetch
 git reset --hard origin/master
-~/src/pip3/bin/pip3 install --upgrade -r ~/SickChill/requirements.txt
-~/src/pip3/bin/pip3 install --upgrade pyopenssl
+~/src/python3/python -m pip install --upgrade -r ~/SickChill/requirements.txt
+~/src/python3/python -m pip install --upgrade pyopenssl
 
 # initial sickchill configuration
 if [ ! -d ~/.SickChill.tv.shows ]; then
   # boot sickchill to setup initial files
-  ~/src/pip3/bin/python ~/SickChill/SickChill.py -d --pidfile="$HOME/SickChill/SickChill.pid"
+  ~/src/python3/python ~/SickChill/SickChill.py -d \
+    --pidfile="$HOME/SickChill/SickChill.pid"
   pkill -9 -fu "$(whoami)" 'SickChill/SickChill.py'
   rm -rf ~/SickChill/SickChill.pid && sleep 10
 
   # generate ~/.SickChill.tv.shows
   mkdir ~/.SickChill.tv.shows
-  sed -ri 's|web_port = (.*)|web_port = '"$(shuf -i 10001-32001 -n 1)"'|g' ~/SickChill/config.ini
-  sed -ri 's|web_root = (.*)|web_root = /'"$(whoami)"'/sickchill|g' ~/SickChill/config.ini
-  sed -ri 's|launch_browser = 1|launch_browser = 0|g' ~/SickChill/config.ini
-  sed -ri 's#root_dirs = (.*)#root_dirs = '"$HOME"'/.SickChill.tv.shows#g' ~/SickChill/config.ini
+  sed -ri 's|web_port = (.*)|web_port = '"$(shuf -i 10001-32001 -n 1)"'|g' \
+    ~/SickChill/config.ini
+  sed -ri 's|web_root = (.*)|web_root = /'"$(whoami)"'/sickchill|g' \
+    ~/SickChill/config.ini
+  sed -ri 's|launch_browser = 1|launch_browser = 0|g' \
+    ~/SickChill/config.ini
+  sed -ri 's#root_dirs = (.*)#root_dirs = '"$HOME"'/.SickChill.tv.shows#g' \
+    ~/SickChill/config.ini
 fi
